from typing import Protocol

from pydantic import BaseModel

from .contracts import WorkflowRun
from .repository_tools import RepositoryExecutionResult


class PullRequestDraft(BaseModel):
    title: str
    body: str
    head: str
    base: str = "main"
    draft: bool = True


class PullRequestPublisher(Protocol):
    def create(self, draft: PullRequestDraft) -> str: ...


def build_pull_request_draft(
    run: WorkflowRun, execution: RepositoryExecutionResult
) -> PullRequestDraft:
    if run.engineering is None or run.planning is None or run.architecture is None:
        raise ValueError("Pull request evidence requires planning, architecture, and engineering")
    if run.qa is None or run.security is None or run.quality_gate is None or run.review is None:
        raise ValueError("Pull request evidence requires completed quality and review stages")
    if run.approval is None or not run.approval.approved:
        raise ValueError("Pull request publication requires explicit human approval")
    if run.ci_validation is None or not run.ci_validation.passed:
        raise ValueError("Pull request publication requires successful executable CI evidence")
    if run.approval.commit_sha != run.ci_validation.commit_sha:
        raise ValueError("Human approval is stale for the validated commit SHA")
    if run.verified_mutation_commit_sha is None:
        raise ValueError("Pull request publication requires verified mutation commit evidence")
    if not (run.verified_mutation_commit_sha == run.ci_validation.commit_sha == run.approval.commit_sha):
        raise ValueError("Mutation, CI, and human approval commit SHAs must be identical")
    if execution.dry_run:
        raise ValueError("Cannot publish a pull request for a dry-run repository execution")
    if execution.branch_name != run.engineering.branch_name:
        raise ValueError("Executed branch does not match Engineering Agent artifact")

    criteria = "\n".join(
        f"- {item.id}: {item.statement}" for item in run.planning.acceptance_criteria
    )
    decisions = "\n".join(
        f"- {item.id}: {item.title} — {item.decision}"
        for item in run.architecture.decisions
    )
    files = "\n".join(f"- `{path}`" for path in execution.applied_paths)
    traceability = "\n".join(
        f"- {item.acceptance_criterion_id}: {'covered' if item.covered else 'missing evidence'}"
        for item in run.review.traceability
    )
    body = f"""## Product request

{run.original_request}

## Business objective

{run.planning.business_objective}

## Acceptance criteria

{criteria}

## Architecture decisions

{decisions}

## Applied change set

{files}

## Independent quality evidence

- QA passed: **{run.qa.passed}**
- Security passed: **{run.security.passed}**
- Deterministic quality gate passed: **{run.quality_gate.passed}**
- Reviewer passed: **{run.review.passed}**

### Traceability

{traceability}

## Human approval

- Approved: **{run.approval.approved}**
- Approver identity: **{run.approval.approver.identity_id}**
- Approver type: **{run.approval.approver.actor_type}**
- Authentication source: **{run.approval.approver.authentication_source}**
- Approval role: **{run.approval.approver.role}**
- Rationale: {run.approval.rationale}
- Timestamp: {run.approval.timestamp.isoformat()}
- Approved commit SHA: `{run.approval.commit_sha}`

## Executable CI evidence

- CI run: **{run.ci_validation.run_id}**
- Validated commit SHA: `{run.ci_validation.commit_sha}`
- CI passed: **{run.ci_validation.passed}**

---
Generated by the AI-Native Engineering Command Center. Merge/deployment remains a separate human-controlled action.
"""
    return PullRequestDraft(
        title=run.engineering.commit_message,
        body=body,
        head=execution.branch_name,
    )
